#Login information for epic fight patron server. Do not change these values manually
access_token = ""
refresh_token = ""
#Allowed Values: NULL, DISCORD, PATREON
provider = "NULL"

[ingame]
	show_target_indicator = true
	#Allowed Values: NONE, HURT, TARGET, TARGET_AND_HURT
	health_bar_show_option = "HURT"
	# Default: 30
	# Range: 0 ~ 30
	max_hit_projectiles = 30
	# Default: 0.328125
	# Range: 0.0 ~ 1.0
	laser_pointer_color = 0.328125
	enable_laser_pointer = true
	blood_effects = true
	aiming_correction = true
	show_epicfight_attributes = true
	use_compute_shader = false
	first_person_model = true
	#Allowed Values: NONE, CROSSHAIR, HIGHLIGHT, CROSSHAIR_AND_HIGHLIGHT
	mine_block_guide_option = "CROSSHAIR"
	enable_target_entity_guide = true
	enable_pov_action = true
	enable_cosmetics = true
	enable_player_vanilla_model = true
	# Default: 2
	# Range: 1 ~ 10
	long_press_count = 2
	camera_auto_switch = false
	#Allowed Values: NONE, INTERACTION, ITEM_USE, INTERACTION_AND_ITEMUSE
	key_conflict_resolve_scope = "INTERACTION"
	#Allowed Values: ADAPTIVE, SWITCH_MODE
	preference_work = "ADAPTIVE"
	combat_preferred_items = []
	mining_preferred_items = []

	[ingame.ui]
		stamina_bar_x = 120
		stamina_bar_y = 10
		#Allowed Values: LEFT, RIGHT, CENTER
		stamina_bar_x_base = "RIGHT"
		#Allowed Values: TOP, BOTTOM, CENTER
		stamina_bar_y_base = "BOTTOM"
		weapon_innate_x = 42
		weapon_innate_y = 48
		#Allowed Values: LEFT, RIGHT, CENTER
		weapon_innate_x_base = "RIGHT"
		#Allowed Values: TOP, BOTTOM, CENTER
		weapon_innate_y_base = "BOTTOM"
		passives_x = 70
		passives_y = 36
		#Allowed Values: LEFT, RIGHT, CENTER
		passives_x_base = "RIGHT"
		#Allowed Values: TOP, BOTTOM, CENTER
		passives_y_base = "BOTTOM"
		#Allowed Values: HORIZONTAL, VERTICAL
		passives_align_direction = "HORIZONTAL"
		charging_bar_x = -119
		charging_bar_y = 60
		#Allowed Values: LEFT, RIGHT, CENTER
		charging_bar_x_base = "CENTER"
		#Allowed Values: TOP, BOTTOM, CENTER
		charging_bar_y_base = "CENTER"
